# Generated by Django 5.0.1 on 2024-01-30 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0002_todo_type_alter_todo_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='type',
        ),
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('complete', 'complete'), ('in-progress', 'in-progress')], default='pending', max_length=225),
        ),
    ]
